# Generated by Django 5.0.3 on 2024-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_inequality_index', models.FloatField()),
                ('maternal_mortality_ratio', models.FloatField()),
                ('adolescent_birth_rate', models.FloatField()),
                ('women_parliament_seats', models.FloatField()),
                ('female_secondary_education', models.FloatField()),
                ('male_secondary_education', models.FloatField()),
                ('female_labour_force', models.FloatField()),
                ('male_labour_force', models.FloatField()),
            ],
        ),
    ]
